### ISSUE TITLE
harvesting: grants and funders updating

### ISSUE THREAD

**Issue by krzysztof** [inveniosoftware/invenio-openaire#7]
At the moment the harvesting tasks does not check whether given record should be updated (i.e. converted JSON differs from the JSON stored in the DB) nor whether it already exists in the database, making it only useful for the initial DB populating but not updating.

Updating should be implemented as a functionality of the current harvesting tasks, not as a separate "update" task.

Possible solutions:
1. Iterate through all OpenAIRE records and check them against the database (costly for frequent updates).
2. If it's possible, fetch only the new additions using OpenAIRE API.

**Comment by lnielsen** [comment]
Implemented in `invenio_openaire.tasks.create_or_update_record`
