### ISSUE TITLE
cli: implement basic CLI

### ISSUE THREAD

**Issue by krzysztof** [inveniosoftware/invenio-openaire#8]
OpenAIRE should provide CLI for the following features:
1. Harvest and update funders (accept both the local path and URL)
2. Harvest and update grants (accept both the local path and the OAI-PMH endpoint)
3. Harvest grants and store them locally
4. Set the reference to funder inside grant JSON (i.e. change funder X of grant Y to funder Z) (identifiable by PID)
5. Set all references to funder X inside all grant JSONs to a funder Y (identifiable by PID)
6. Set a funder's parent (identifiable by PID)

**Comment by lnielsen** [comment]
I think this is done.
